files: '{{cookiecutter.project_slug}}'
repos:
-   repo: https://github.com/psf/black.git
    rev: 23.10.0
    hooks:
    -   id: black
-   repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.1.0
    hooks:
    -   id: ruff
        args: [--fix]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-pytz]
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
